_wandb:
    value:
        cli_version: 0.19.4
        m: []
        python_version: 3.10.15
        t:
            "1":
                - 1
                - 5
                - 11
                - 30
                - 49
                - 53
                - 55
                - 75
            "2":
                - 1
                - 5
                - 11
                - 30
                - 49
                - 53
                - 55
                - 75
            "3":
                - 1
                - 2
                - 3
                - 16
                - 23
                - 55
            "4": 3.10.15
            "5": 0.19.4
            "6": 4.48.1
            "8":
                - 5
            "12": 0.19.4
            "13": darwin-arm64
batch_size:
    value: 64
epochs:
    value: 100
learning_rate:
    value: 0.0001
max_grad_norm:
    value: 1
min_delta:
    value: 0.0001
model_name:
    value: club_recommender
patience:
    value: 15
use_cache:
    value: true
validation_split:
    value: 0.2
wandb_project:
    value: club-recommender
